spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/softdesigndesafio
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        id:
          new_generator_mappings: false
  redis:
    host: localhost
    port: 6379
    timeout: 2000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    cache:
      time-to-live: 600000
  cache:
    type: redis

server:
  port: 8080
